- name: Deploy Firestore Rules (if requested)
  if: github.event_name == 'workflow_dispatch' && (github.event.inputs.target == 'rules' || github.event.inputs.target == 'both') || startsWith(github.ref, 'refs/tags/v')
  working-directory: gst-report-generator-web
  run: |
    firebase deploy --only firestore:rules --project $PROJECT_ID
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

- name: Deploy Hosting (production or preview)
  if: github.event_name == 'workflow_dispatch' && (github.event.inputs.target == 'hosting' || github.event.inputs.target == 'both') || startsWith(github.ref, 'refs/tags/v')
  working-directory: gst-report-generator-web
  run: |
    if [ -n "${{ github.event.inputs.channel }}" ]; then
      echo "Deploying to preview channel: ${{ github.event.inputs.channel }}"
      firebase hosting:channel:deploy "${{ github.event.inputs.channel }}" --project $PROJECT_ID --expires 30d
    else
      echo "Deploying to production (live)"
      firebase deploy --only hosting --project $PROJECT_ID
    fi
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
